/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * DVB-S2X Physical Layer Scrambler
 *
 * Scrambles the data portion of PL frames using a Gold sequence.
 * The scrambling sequence is generated by two LFSRs:
 *   x: x^18 + x^7 + 1
 *   y: x^18 + x^5 + x^2 + x + 1
 *
 * The Gold sequence index determines the initialization of the
 * y-sequence LFSR.
 *
 * Reference: ETSI EN 302 307-1 clause 5.5.4
 */

#ifndef DVBS2X_SCRAMBLER_H
#define DVBS2X_SCRAMBLER_H

#include "dvbs2x_types.h"

/* LFSR register length */
#define DVBS2X_SCRAMBLER_REG_LEN	18

/* Maximum scrambling code index */
#define DVBS2X_SCRAMBLER_MAX_IDX	148574

/* Scrambler state */
struct dvbs2x_scrambler {
	uint32_t	x_reg;
	uint32_t	y_reg;
	unsigned int	gold_idx;
};

/*
 * dvbs2x_scrambler_init - Initialize scrambler with Gold code index
 * @scr: scrambler state
 * @gold_idx: Gold sequence index (0 to 148574)
 *
 * The PL scrambling index for VL-SNR is typically 0-7.
 */
void dvbs2x_scrambler_init(struct dvbs2x_scrambler *scr,
			   unsigned int gold_idx);

/*
 * dvbs2x_scrambler_reset - Reset scrambler to initial state
 * @scr: scrambler state (must have been initialized)
 */
void dvbs2x_scrambler_reset(struct dvbs2x_scrambler *scr);

/*
 * dvbs2x_scramble - Scramble complex symbols in place
 * @scr: scrambler state
 * @symbols: symbols to scramble (modified in place)
 * @len: number of symbols
 *
 * Each symbol is multiplied by a complex scrambling value
 * derived from two consecutive Gold sequence bits:
 *   (0,0) -> +1+0j
 *   (0,1) -> +0+1j
 *   (1,0) -> -1+0j
 *   (1,1) -> +0-1j
 */
void dvbs2x_scramble(struct dvbs2x_scrambler *scr,
		     struct dvbs2x_complex *symbols,
		     unsigned int len);

/*
 * dvbs2x_descramble - Descramble complex symbols in place
 * @scr: scrambler state
 * @symbols: symbols to descramble (modified in place)
 * @len: number of symbols
 *
 * Applies conjugate of scrambling sequence.
 */
void dvbs2x_descramble(struct dvbs2x_scrambler *scr,
		       struct dvbs2x_complex *symbols,
		       unsigned int len);

#endif /* DVBS2X_SCRAMBLER_H */
